# Refinex Gateway 服务配置

spring:
  main:
    # 显式声明 WebFlux 环境（防止外部配置污染）
    web-application-type: reactive
  cloud:
    gateway:
      # 自定义属性，是否开启请求日志, 默认开启
      request-log: true
      server:
        webflux:
          routes:
            # 认证服务路由
            - id: auth
              uri: lb://auth
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=0

            # 平台服务路由
            - id: platform
              uri: lb://platform
              predicates:
                - Path=/platform/**
              filters:
                - StripPrefix=0

# 网关安全配置
security:
  ignore:
    # 白名单列表, 网关将忽略这些路径的认证
    whites:
      - /auth/login
      - /auth/register
      - /auth/logout
      - /auth/captcha/generate
      - /favicon.ico
      - /actuator/**
      - /doc.html
      - /swagger-ui/**
      - /v3/api-docs/**

# # Gateway 聚合 Swagger 文档
knife4j:
  gateway:
    enable: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enable: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : openapi3