# Refinex Gateway 服务配置

spring:
  main:
    # 显式声明 WebFlux 环境（防止外部配置污染）
    web-application-type: reactive

  # 配置 Jackson 日期格式化
  jackson:
    # 定义日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 定义序列化配置
    serialization:
      # 定义是否缩进输出
      indent-output: false
      # 定义是否在序列化时失败时抛出异常
      fail-on-empty-beans: false
    # 定义反序列化配置
    deserialization:
      # 定义是否在反序列化时未知属性失败时抛出异常
      fail-on-unknown-properties: false

  data:
    # 定义 Redis 相关配置
    redis:
      # 定义 Redis 主机地址
      host: 180.184.71.201
      # 定义 Redis 端口号
      port: 16379
      # 定义 Redis 密码, 默认空字符串
      password: Ly084073.
      # 定义 Redis 数据库索引, 默认 0
      database: 0
      # 定义 Redis 连接超时时间, 单位毫秒
      timeout: 10s
      # 定义 Lettuce 连接池配置
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间 (使用负值表示没有限制)
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # 认证服务路由
            - id: refinex-auth
              uri: lb://refinex-auth
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=0

            # 平台服务路由
            - id: refinex-platform
              uri: lb://refinex-platform
              predicates:
                - Path=/platform/**
              filters:
                - StripPrefix=0

# 网关安全配置
gateway:
  security:
    # 启用鉴权
    enabled: true
    # 启用日志
    log-enabled: true
    # 白名单路径（不需要认证）
    whitelist-paths:
      - /feign-api/**
      - /auth/login
      - /auth/register
      - /captcha/generate
      - /favicon.ico
      - /actuator/**
      - /doc.html
      - /swagger-ui/**
      - /v3/api-docs/**

# # Gateway 聚合 Swagger 文档
knife4j:
  gateway:
    enable: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enable: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : openapi3