# Refinex Gateway 服务配置

spring:
  main:
    # 显式声明 WebFlux 环境（防止外部配置污染）
    web-application-type: reactive
  cloud:
    gateway:
      # 自定义属性，是否开启请求日志, 默认开启
      request-log: true
      server:
        webflux:
          routes:
            # 认证服务路由
            - id: refinex-auth
              uri: lb://refinex-auth
              predicates:
                - Path=/refinex-auth/**
              filters:
                # 去掉第一个路径前缀, 即服务名(0: 不去掉任何路径段 1: 去掉第一个路径段 2: 去掉前两个路径段，以此类推)
                - StripPrefix=1

            # 平台服务路由
            - id: refinex-platform
              uri: lb://refinex-platform
              predicates:
                - Path=/refinex-platform/**
              filters:
                - StripPrefix=1

# 网关安全配置
security:
  ignore:
    # 白名单列表, 网关将忽略这些路径的认证
    whites:
      - /refinex-auth/**
      - /favicon.ico
      - /actuator/**
      - /doc.html
      - /swagger-ui/**
      - /v3/api-docs/**

# # Gateway 聚合 Swagger 文档
knife4j:
  gateway:
    enable: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enable: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : openapi3