# Refinex Auth 服务配置

spring:
  # 数据源配置
  datasource:
    dynamic:
      datasource:
        # 主数据源（refinex_platform 数据库）
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/refinex_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: 123456

refinex:
  # 自定义安全配置
  security:
    # 启用安全模块
    enabled: true
    # 缓存配置
    cache:
      # 启用缓存
      enabled: true
      # 缓存过期时间（秒）
      ttl: 1800

  # 验证码配置
  captcha:
    # 是否启用验证码
    enabled: true
    # 验证码类型
    # 可选值：
    #   - spec: PNG 类型（线段干扰）
    #   - gif: GIF 动画类型
    #   - arithmetic: 算术验证码
    #   - chinese: 中文验证码
    #   - chinese_gif: 中文 GIF 验证码
    type: spec
    # 图片宽度
    width: 130
    # 图片高度
    height: 48
    # 验证码长度（字符数）
    length: 4
    # 过期时间（秒）
    expire-seconds: 300
    # 字符类型
    # 可选值：
    #   - 0: 数字和字母混合
    #   - 1: 纯数字
    #   - 2: 纯字母
    #   - 3: 纯大写字母
    #   - 4: 纯小写字母
    #   - 5: 数字和大写字母
    char-type: 2
    # 是否区分大小写
    case-sensitive: false
    # 字体（1-10）
    font: 1
    # Redis Key 前缀
    redis-key-prefix: "captcha:"