spring:
  # 定义 Jackson 相关配置
  jackson:
    # 定义日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 定义序列化配置
    serialization:
      # 定义是否缩进输出
      indent-output: false
      # 定义是否在序列化时失败时抛出异常
      fail-on-empty-beans: false
    # 定义反序列化配置
    deserialization:
      # 定义是否在反序列化时未知属性失败时抛出异常
      fail-on-unknown-properties: false

  threads:
    virtual:
      # 开启虚拟线程, JDK >= 21
      enabled: true

  task:
    execution:
      # 定义任务执行线程名称前缀
      thread-name-prefix: task-
      # 由 Spring 管理任务执行线程池, SpringBoot 3.5+ SpringBoot 会自动配置线程池
      mode: force

  data:
    # 定义 Redis 相关配置
    redis:
      # 定义 Redis 主机地址
      host: 127.0.0.1
      # 定义 Redis 端口号
      port: 6379
      # 定义 Redis 密码, 默认空字符串
      # password:
      # 定义 Redis 数据库索引, 默认 0
      database: 0
      # 定义 Redis 连接超时时间, 单位毫秒
      timeout: 10s
      # 定义 Lettuce 连接池配置
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间 (使用负值表示没有限制)
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

# Sa-Token 相关配置
sa-token:
  # Token 名称, 同时也是 Cookie 名称
  token-name: Authorization
  # Token 有效期, 单位：秒, 默认 30 天, -1 代表永久有效
  # 本系统设置为 30 分钟, 通过 Token 续期进行扩展
  timeout: 1800
  # Token 最低活跃频率, 单位：秒, 如果 Token 超过此时间没有访问系统就会被冻结, 默认 -1 代表不限制永不冻结
  # 本系统设置为 30 分钟, 超过 30 分钟未访问系统就会被冻结
  active-timeout: 1800
  # 是否允许同一账号并发登录, true：允许一起登录, false：新登录挤掉旧登录
  is-concurrent: true
  # 在多人登录同一账号时是否共用一个 Token, true：所有登录共用一个 Token, false：每次登录新建一个 Token
  is-share: false
  # Token 风格 (可选值：uuid、simple-uuid、random-32、random-64、random-128、tik、jwt-simple)
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 开启内网服务调用鉴权, 不允许越过 Gateway 访问内网服务, 保障服务安全
  check-same-token: true

# Logback 配置
logging:
  logback:
    # 定义日志滚动策略
    rollingpolicy:
      # 定义日志文件最大大小
      max-file-size: 100MB
      # 定义是否在启动时清理历史日志文件
      clean-history-on-start: true
      # 定义日志文件总大小上限
      total-size-cap: 1GB
      # 定义保留的最大历史日志文件数量
      max-history: 7
  level:
    org.springframework: warn
    com.alibaba.nacos: error
    org.apache.fury: warn
    io.micrometer: error

# Redisson 相关配置
redisson:
  # 定义 Redisson 键前缀
  key-prefix:
  # 定义 Redisson 线程数
  threads: 4
  # 定义 Redisson Netty 线程数
  netty-threads: 8
  # 定义 Redisson 单节点配置
  single-server-config:
    # 定义 Redisson 客户端名称
    client-name: ${spring.application.name}
    # 定义 Redisson 连接池大小
    connection-pool-size: 32
    # 定义 Redisson 连接池最小空闲连接数
    connection-minimum-idle-size: 8
    # 定义 Redisson 连接超时时间, 单位毫秒
    idle-connection-timeout: 10000
    # 定义 Redisson 连接超时时间, 单位毫秒
    timeout: 3000
    # 定义 Redisson 订阅连接池大小
    subscription-connection-pool-size: 50

# Lock4J 相关配置
lock4j:
  # 定义获取锁的超时时间, 单位毫秒
  acquire-timeout: 3000
  # 定义锁的过期时间, 单位毫秒
  expire: 30000

# Xss 相关配置
xss:
  # 定义是否开启 Xss 过滤
  enabled: true
  # 定义要排除的路径
  exclude-paths:
    - /platform/notice

# Api Doc 相关配置
springdoc:
  api-doc:
    # 定义是否开启 Api Doc
    enabled: true
  info:
    # 定义 Api Doc 标题
    title: Refinex API Doc
    # 定义 Api Doc 描述
    description: Refinex API Doc
    # 定义 Api Doc 版本
    version: 1.0.0
    # 定义 Api Doc 联系人
    contact:
      # 定义 Api Doc 联系人名称
      name: Refinex
      # 定义 Api Doc 联系人邮箱
      email: refinex@gmail.com
      # 定义 Api Doc 联系人 URL
      url: https://refinex.cn

# Refinex 相关配置
refinex:
  # Xss 过滤配置
  xss:
    # 是否开启 Xss 过滤
    enabled: true
    # 定义要排除的路径
    exclude-paths:
      # 不处理 Actuator 的请求
      - ${management.endpoints.web.base-path}/**

  # Swagger 配置
  swagger:
    # 是否开启 Swagger
    enabled: true
    # 标题
    title: Refinex API Doc
    # 描述
    description: Refinex API Doc
    # 版本
    version: 1.0.0
    # 联系人名称
    contact-name: Refinex
    # 联系人邮箱
    contact-email: refinex@gmail.com
    # 联系人 URL
    contact-url: https://refinex.cn
    # 许可证
    license: Apache 2.0
    # 许可证 URL
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html