# Refinex Platform 服务配置
spring:
  datasource:
    dynamic:
      # 是否启用严格模式（默认 false）
      strict: false
      # 主数据源配置
      primary: master
      datasource:
        # 主库配置
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/refinex_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 123456
          # HikariCP 连接池配置
          hikari:
            minimum-idle: 5
            maximum-pool-size: 20
            idle-timeout: 600000
            max-lifetime: 1800000
            connection-timeout: 30000

# 自定义安全配置
refinex:
  security:
    # 是否启用安全认证
    enabled: true
    # 是否启用 Feign 日志
    feign-log-enabled: true
    # 缓存配置
    cache:
      # 是否启用缓存
      enabled: true
      # 缓存过期时间（秒）
      ttl: 1800

# Swagger 文档配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: Refinex Platform API
    description: Refinex 平台服务 API 文档
    version: 1.0.0
    contact:
      name: Refinex Team
      email: support@refinex.cn

