# Refinex Gateway 服务配置

spring:
  main:
    # 显式声明 WebFlux 环境（防止外部配置污染）
    web-application-type: reactive
  cloud:
    gateway:
      # 自定义属性，是否开启请求日志, 默认开启
      request-log: true
      server:
        webflux:
          routes:
            # 认证服务路由
            - id: refinex-auth
              uri: lb://refinex-auth
              predicates:
                - Path=/refinex-auth/**
              filters:
                # 去掉第一个路径前缀, 即服务名(0: 不去掉任何路径段 1: 去掉第一个路径段 2: 去掉前两个路径段，以此类推)
                - StripPrefix=1

            # 平台服务路由
            - id: refinex-platform
              uri: lb://refinex-platform
              predicates:
                - Path=/refinex-platform/**
              filters:
                - StripPrefix=1

            # 知识库服务路由
            - id: refinex-kb
              uri: lb://refinex-kb
              predicates:
                - Path=/refinex-kb/**
              filters:
                - StripPrefix=1

            # 智能体服务路由
            - id: refinex-ai
              uri: lb://refinex-ai
              predicates:
                - Path=/refinex-ai/**
              filters:
                - StripPrefix=1

# 网关安全配置
security:
  ignore:
    # 白名单列表, 网关将忽略这些路径的认证
    whites:
      - /refinex-auth/**
      - /refinex-platform/logger/async
      - /favicon.ico
      - /actuator/**
      - /doc.html
      - /swagger-ui/**
      - /v3/api-docs/**

# Knife4j 网关聚合配置
knife4j:
  gateway:
    # 是否启用 Knife4j 网关聚合
    enable: true

    # 排序规则
    tags-sorter: order
    operations-sorter: order

    # 聚合策略: manual-手动配置, discover-服务发现(自动聚合所有服务)
    strategy: discover

    # 服务发现配置
    discover:
      enable: true
      # 指定版本号(openapi3|swagger2)
      version : openapi3

      # 排除的服务(网关本身、非业务服务等)
      excluded-services:
        - refinex-gateway

      # OpenAPI3 配置
      oas3:
        url: /v3/api-docs