spring:
  # 定义 Servlet 相关配置
  servlet:
    multipart:
      # 定义上传文件的最大请求大小
      max-request-size: 20MB
      # 定义上传文件的最大大小
      max-file-size: 50MB
  # 定义 MVC 相关配置
  mvc:
    # 定义静态资源的路径模式
    static-path-pattern: /static/**
    format:
      # 定义日期时间格式
      date-time: yyyy-MM-dd HH:mm:ss
  # 定义 Jackson 相关配置
  jackson:
    # 定义日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 定义序列化配置
    serialization:
      # 定义是否缩进输出
      indent-output: false
      # 定义是否在序列化时失败时抛出异常
      fail-on-empty-beans: false
    # 定义反序列化配置
    deserialization:
      # 定义是否在反序列化时未知属性失败时抛出异常
      fail-on-unknown-properties: false
  threads:
    virtual:
      # 开启虚拟线程, JDK >= 21
      enabled: true
  task:
    execution:
      # 定义任务执行线程名称前缀
      thread-name-prefix: task-
      # 由 Spring 管理任务执行线程池, SpringBoot 3.5+ SpringBoot 会自动配置线程池
      mode: force
  data:
    # 定义 Redis 相关配置
    redis:
      # 定义 Redis 主机地址
      host: localhost
      # 定义 Redis 端口号
      port: 6379
      # 定义 Redis 密码
      password: 123456
      # 定义 Redis 数据库索引
      database: 0
      # 定义 Redis 连接超时时间, 单位毫秒
      timeout: 10000
      # 定义 Redis SSL 配置
      ssl:
        # 定义是否启用 Redis SSL
        enabled: false
  # 定义数据源相关配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      # 定义默认数据源
      default-datasource: master
      # 严格匹配数据源, 未匹配到数据源时抛出异常
      strict: true
      # 定义 Hikari 连接池配置
      hikari:
        # 定义最大连接数
        maximum-pool-size: 20
        # 定义最小空闲连接数
        minimum-idle: 10
        # 定义连接超时时间, 单位毫秒
        connection-timeout: 30000
        # 定义空闲连接超时时间, 单位毫秒
        idle-timeout: 600000
        # 定义最大生命周期, 单位毫秒
        max-lifetime: 1800000
        # 定义保持连接活动的时间, 单位毫秒
        keepalive-time: 30000
        # 定义验证连接是否活动的超时时间, 单位毫秒
        validation-timeout: 5000

# Sa-Token 相关配置
satoken:
  # token 名称 (同时也是 cookie 名称)
  token-name: Authorization
  # 开启内网服务调用鉴权(不允许越过 Gateway 访问内网服务 保障服务安全)
  check-same-token: true
  # 是否允许同一账号并发登录(为 true 时允许一起登录, 为 false 时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时是否共用一个 token (为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token)
  is-share: false
  # jwt 秘钥
  jwt-secret-key: abcdefghijklmnopqrstuvwxyz

# Logback 配置
logging:
  logback:
    # 定义日志滚动策略
    rollingpolicy:
      # 定义日志文件最大大小
      max-file-size: 100MB
      # 定义是否在启动时清理历史日志文件
      clean-history-on-start: true
      # 定义日志文件总大小上限
      total-size-cap: 1GB
      # 定义保留的最大历史日志文件数量
      max-history: 7
  level:
    org.springframework: warn
    com.alibaba.nacos: error
    org.apache.fury: warn
    io.micrometer: error

# Redisson 相关配置
redisson:
  # 定义 Redisson 键前缀
  key-prefix:
  # 定义 Redisson 线程数
  threads: 4
  # 定义 Redisson Netty 线程数
  netty-threads: 8
  # 定义 Redisson 单节点配置
  single-server-config:
    # 定义 Redisson 客户端名称
    client-name: ${spring.application.name}
    # 定义 Redisson 连接池大小
    connection-pool-size: 32
    # 定义 Redisson 连接池最小空闲连接数
    connection-minimum-idle-size: 8
    # 定义 Redisson 连接超时时间, 单位毫秒
    idle-connection-timeout: 10000
    # 定义 Redisson 连接超时时间, 单位毫秒
    timeout: 3000
    # 定义 Redisson 订阅连接池大小
    subscription-connection-pool-size: 50

# Lock4J 相关配置
lock4j:
  # 定义获取锁的超时时间, 单位毫秒
  acquire-timeout: 3000
  # 定义锁的过期时间, 单位毫秒
  expire: 30000

# Xss 相关配置
xss:
  # 定义是否开启 Xss 过滤
  enabled: true
  # 定义要排除的路径
  exclude-paths:
    - /platform/notice

# Api Doc 相关配置
springdoc:
  api-doc:
    # 定义是否开启 Api Doc
    enabled: true
  info:
    # 定义 Api Doc 标题
    title: Refinex API Doc
    # 定义 Api Doc 描述
    description: Refinex API Doc
    # 定义 Api Doc 版本
    version: 1.0.0
    # 定义 Api Doc 联系人
    contact:
      # 定义 Api Doc 联系人名称
      name: Refinex
      # 定义 Api Doc 联系人邮箱
      email: refinex@gmail.com
      # 定义 Api Doc 联系人 URL
      url: https://refinex.cn