spring:
  # 定义 Servlet 相关配置
  servlet:
    multipart:
      # 定义上传文件的最大请求大小
      max-request-size: 20MB
      # 定义上传文件的最大大小
      max-file-size: 50MB
  # 定义 MVC 相关配置
  mvc:
    # 定义静态资源的路径模式
    static-path-pattern: /static/**
    format:
      # 定义日期时间格式
      date-time: yyyy-MM-dd HH:mm:ss

  # 定义数据源相关配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      # 定义默认数据源
      default-datasource: master
      # 严格匹配数据源, 未匹配到数据源时抛出异常
      strict: true
      # 定义 Hikari 连接池配置
      hikari:
        # 定义最大连接数
        maximum-pool-size: 20
        # 定义最小空闲连接数
        minimum-idle: 10
        # 定义连接超时时间, 单位毫秒
        connection-timeout: 30000
        # 定义空闲连接超时时间, 单位毫秒
        idle-timeout: 600000
        # 定义最大生命周期, 单位毫秒
        max-lifetime: 1800000
        # 定义保持连接活动的时间, 单位毫秒
        keepalive-time: 30000
        # 定义验证连接是否活动的超时时间, 单位毫秒
        validation-timeout: 5000

# Feign 配置
feign:
  client:
    config:
      default:
        # 连接超时时间（毫秒）
        connect-timeout: 5000
        # 读取超时时间（毫秒）
        read-timeout: 10000
        # 日志级别
        logger-level: basic
  # 启用 Sentinel 熔断降级
  sentinel:
    enabled: false
  # 启用压缩
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

# Refinex 相关配置
refinex:
  # 文件存储配置
  file:
    # 是否启用文件存储模块
    enabled: true
    # 默认存储类型（S3、OSS、COS、KODO、MINIO、DATABASE）
    default-storage-type: S3

    # 上传配置
    upload:
      # 最大文件大小（支持单位：KB、MB、GB）
      max-file-size: 100MB
      # 允许的文件扩展名（为空表示不限制）
      allowed-extensions:
        # 图片类型
        - jpg
        - jpeg
        - png
        - gif
        - bmp
        - webp
        - svg
        # 文档类型
        - pdf
        - doc
        - docx
        - xls
        - xlsx
        - ppt
        - pptx
        - txt
        - md
        # 压缩包类型
        - zip
        - rar
        - 7z
        - tar
        - gz
        # 视频类型
        - mp4
        - avi
        - mov
        - wmv
        - flv
        # 音频类型
        - mp3
        - wav
        - flac
        - aac
      # 分片大小（用于大文件分片上传）
      chunk-size: 5MB

    # 下载配置
    download:
      # 预签名 URL 过期时间（支持单位：s、m、h、d）
      presigned-url-expiration: 1h

    # 图片配置
    image:
      # 缩略图宽度（像素）
      thumbnail-width: 300
      # 缩略图高度（像素）
      thumbnail-height: 300
      # 缩略图格式（webp、jpg、png）
      thumbnail-format: webp

    # 存储配置（可选，优先使用数据库配置）
    # 注意：生产环境建议将存储配置保存到数据库的 file_storage_config 表中
    # 此处配置仅用于开发测试或作为默认配置
    storage:
      # S3 存储配置示例
      s3:
        # 访问密钥（建议使用环境变量注入）
        access-key: ${S3_ACCESS_KEY:your-access-key}
        # 访问密钥（建议使用环境变量注入）
        secret-key: ${S3_SECRET_KEY:your-secret-key}
        # 区域
        region: us-east-1
        # 存储桶名称
        bucket-name: refinex-files
        # 访问端点 URL（可选，用于兼容 MinIO 等 S3 兼容存储）
        endpoint: https://s3.amazonaws.com
        # 基础路径前缀（可选）
        base-path: /uploads
        # 访问域名（可选，用于生成访问 URL）
        domain-url: https://cdn.refinex.cn

      # 阿里云 OSS 存储配置示例
      oss:
        access-key: ${OSS_ACCESS_KEY:your-access-key}
        secret-key: ${OSS_SECRET_KEY:your-secret-key}
        region: oss-cn-hangzhou
        bucket-name: refinex-files
        endpoint: https://oss-cn-hangzhou.aliyuncs.com
        base-path: /uploads
        domain-url: https://cdn.refinex.cn

      # 腾讯云 COS 存储配置示例
      cos:
        access-key: ${COS_ACCESS_KEY:your-access-key}
        secret-key: ${COS_SECRET_KEY:your-secret-key}
        region: ap-guangzhou
        bucket-name: refinex-files
        endpoint: https://cos.ap-guangzhou.myqcloud.com
        base-path: /uploads
        domain-url: https://cdn.refinex.cn

      # 七牛云 Kodo 存储配置示例
      kodo:
        access-key: ${KODO_ACCESS_KEY:your-access-key}
        secret-key: ${KODO_SECRET_KEY:your-secret-key}
        region: cn-east-1
        bucket-name: refinex-files
        endpoint: https://s3-cn-east-1.qiniucs.com
        base-path: /uploads
        domain-url: https://cdn.refinex.cn

      # MinIO 存储配置示例
      minio:
        access-key: ${MINIO_ACCESS_KEY:minioadmin}
        secret-key: ${MINIO_SECRET_KEY:minioadmin}
        region: us-east-1
        bucket-name: refinex-files
        endpoint: http://localhost:9000
        base-path: /uploads
        domain-url: http://localhost:9000

  # 邮件配置
  mail:
    # 是否启用邮件功能
    enabled: true
    # 默认 SMTP 配置 ID
    default-smtp: default

    # 验证码配置
    verify-code:
      # 验证码有效期（分钟）
      expire-minutes: 5
      # 验证码长度
      code-length: 6
      # 验证码类型（NUMERIC、ALPHA、ALPHANUMERIC）
      code-type: NUMERIC
      # 验证码邮件模板编码
      template-code: VERIFY_CODE
      # 验证码过期检查 Cron 表达式（每小时整点执行）
      expire-check-cron: "0 0 * * * ?"
      # 频率限制配置
      rate-limit:
        # 是否启用频率限制
        enabled: true
        # 同一邮箱每分钟发送次数
        email-per-minute: 1
        # 同一 IP 每分钟发送次数
        ip-per-minute: 5

    # 队列配置
    queue:
      # 是否启用队列功能
      enabled: true
      # 队列扫描间隔（秒）
      scan-interval-seconds: 10
      # 每次处理数量
      batch-size: 50
      # 定时任务扫描间隔（秒）
      scheduled-scan-interval-seconds: 30
      # 失败重试扫描间隔（秒，默认 5 分钟）
      retry-scan-interval-seconds: 300

    # 重试配置
    retry:
      # 是否启用重试
      enabled: true
      # 最大重试次数
      max-attempts: 3
      # 退避倍数
      backoff-multiplier: 2
      # 初始重试间隔（秒）
      initial-interval-seconds: 60

    # SMTP 配置列表
    smtp-configs:
      # 默认配置（QQ 邮箱示例）
      # 配置唯一标识
      - config-id: default
        # SMTP 服务器地址
        host: smtp.qq.com
        # SMTP 端口（25/465/587）
        port: 587
        # 发件人邮箱账号
        username: ${MAIL_USERNAME:your-email@qq.com}
        # 发件人邮箱密码/授权码
        password: ${MAIL_PASSWORD:your-authorization-code}
        # 发件人邮箱地址
        from: ${MAIL_FROM:your-email@qq.com}
        # 发件人显示名称
        from-name: Refinex Cloud
        # 协议（默认 smtp）
        protocol: smtp
        # 默认编码（默认 UTF-8）
        default-encoding: UTF-8
        # JavaMail 额外属性
        properties:
          # 启用 SMTP 认证
          mail.smtp.auth: true
          # 启用 STARTTLS
          mail.smtp.starttls.enable: true
          # 要求 STARTTLS
          mail.smtp.starttls.required: true
          # 连接超时（毫秒）
          mail.smtp.connectiontimeout: 5000
          # 读取超时（毫秒）
          mail.smtp.timeout: 3000
          # 写入超时（毫秒）
          mail.smtp.writetimeout: 5000

      # 163 邮箱配置示例
      - config-id: netease
        host: smtp.163.com
        port: 465
        username: ${MAIL_163_USERNAME:your-email@163.com}
        password: ${MAIL_163_PASSWORD:your-authorization-code}
        from: ${MAIL_163_FROM:your-email@163.com}
        from-name: Refinex Cloud
        protocol: smtp
        default-encoding: UTF-8
        properties:
          mail.smtp.auth: true
          mail.smtp.ssl.enable: true
          mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
          mail.smtp.socketFactory.port: 465
          mail.smtp.connectiontimeout: 5000
          mail.smtp.timeout: 3000
          mail.smtp.writetimeout: 5000

      # 企业邮箱配置示例
      - config-id: enterprise
        host: smtp.exmail.qq.com
        port: 465
        username: ${MAIL_ENTERPRISE_USERNAME:your-email@company.com}
        password: ${MAIL_ENTERPRISE_PASSWORD:your-password}
        from: ${MAIL_ENTERPRISE_FROM:your-email@company.com}
        from-name: Refinex Cloud
        protocol: smtp
        default-encoding: UTF-8
        properties:
          mail.smtp.auth: true
          mail.smtp.ssl.enable: true
          mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
          mail.smtp.socketFactory.port: 465
          mail.smtp.connectiontimeout: 5000
          mail.smtp.timeout: 3000
          mail.smtp.writetimeout: 5000